### PR TITLE
Fix window borders

### PR DESCRIPTION
**Pull request by grulja**
Alternative solution to https://github.com/FedoraQt/QAdwaitaDecorations/pull/69.

### CODE REVIEW

**Comment by bertini97** [comment]
Thank you for taking the time to look into this. This commit produces the following on my end:

Schermata del 2024-06-18 11-07-33

There are grey rectangles coming out the window at the bottom; when I have time I'll look into why this happens. Also, without antialiasing, at around menubar height, the rounded rectangle used for the title bar leaks in the window border.

**Comment by grulja** [comment]
Thanks for testing, I didn't notice this as I was testing in Weston with a small window size and running `Wireshark` it didn't fit there completely so I didn't see it. Trying an app with a smaller window I can reproduce and fixed it now.

**Comment by grulja** [comment]
Can you please check if it works with antialising now?

**Comment by bertini97** [comment]
It works!

**Pull request merged**
