### PR TITLE
Add pressed state for windows buttons

### LINKED ISSUE #60: Missing "pressed" state for window buttons
The minimize/maximize/close controls in Libadwaita use an additional state and background color when being clicked or held. Currently, this is missing from QAdwaitaDecorations. Since this would require new supporting code and is beyond the scope of a simple color change, it was requested to be opened as its own issue.

For reference, light: `#c2c2c2`, dark: `#6e6e6e`.
image
image

### PR DESCRIPTION
**Pull request by grulja**
Fixes #60

### CODE REVIEW

**Comment by grulja** [comment]
@theboctor can you please test? :)

**Comment by TheBoctor** [comment]
image
image
The colors all appear consistent with the screenshots in #60, and the pressed state mostly works as expected.

However, if the user clicks and drags outside of a button to trigger maximization, as described in #58, any further left clicks inside the Qt app window will cause the last pressed button to assume the pressed color. This persists until one of the buttons is clicked and released, without the cursor leaving its area.

**Comment by grulja** [comment]
> However, if the user clicks and drags outside of a button to trigger maximization, as described in #58, any further left clicks inside the Qt app window will cause the last pressed button to assume the pressed color. This persists until one of the buttons is clicked and released, without the cursor leaving its area.

What about now?

**Comment by TheBoctor** [comment]
Looks good now. The pressed color changes back to normal as expected, as soon as the user interacts with the window.

**Comment by grulja** [comment]
> Looks good now. The pressed color changes back to normal as expected, as soon as the user interacts with the window.

Thanks for testing. I tested it myself before, it's not like I'm blindly pushing changes, but I wanted someone to double-check and I'm glad I did that, because you spotted an issue.

**Comment by TheBoctor** [comment]
> > Looks good now. The pressed color changes back to normal as expected, as soon as the user interacts with the window.
> 
> Thanks for testing. I tested it myself before, it's not like I'm blindly pushing changes, but I wanted someone to double-check and I'm glad I did that, because you spotted an issue.

No worries. I assumed you were also checking everything, but an extra set of eyes never hurts. Thanks for fixing this.

**Pull request merged**
